test

diff --git a/.buildspecs/run-tests.yaml b/.buildspecs/run-tests.yaml
--- a/.buildspecs/run-tests.yaml
+++ b/.buildspecs/run-tests.yaml
@@ -10,27 +10,27 @@ phases:
     commands:
       - echo "Running integration tests..."
       - npm test
-  post_build:
-    commands:
-      - |
-        if [ $? -eq 0 ]; then
-          STATUS="SUCCESS"
-        else
-          STATUS="FAILED"
-        fi
-        send_slack_notification() {
-          local status=$1
-          local message
-          if [ "$status" = "SUCCESS" ]; then
-            message="✅ *Build Succeeded* : The integration tests passed successfully."
-          else
-            message="🚫 *Build Failed* : The integration tests failed."
-          fi
-          echo "Sending Slack notification: $message"
-          curl -X POST -H 'Content-type: application/json' \
-            --data "{\"text\":\"${message}\"}" "$SLACK_WEBHOOK_URL"
-        }
-        send_slack_notification "$STATUS"
+#  post_build:
+#    commands:
+#      - |
+#        if [ $? -eq 0 ]; then
+#          STATUS="SUCCESS"
+#        else
+#          STATUS="FAILED"
+#        fi
+#        send_slack_notification() {
+#          local status=$1
+#          local message
+#          if [ "$status" = "SUCCESS" ]; then
+#            message="✅ *Build Succeeded* : The integration tests passed successfully."
+#          else
+#            message="🚫 *Build Failed* : The integration tests failed."
+#          fi
+#          echo "Sending Slack notification: $message"
+#          curl -X POST -H 'Content-type: application/json' \
+#            --data "{\"text\":\"${message}\"}" "$SLACK_WEBHOOK_URL"
+#        }
+#        send_slack_notification "$STATUS"
 artifacts:
   files:
     - "**/*"
