fix

diff --git a/.buildspecs/run-tests.yaml b/.buildspecs/run-tests.yaml
--- a/.buildspecs/run-tests.yaml
+++ b/.buildspecs/run-tests.yaml
@@ -2,7 +2,6 @@ version: 0.2
 env:
   variables:
     SLACK_CHANNEL_ID: C082CSTJ2J2
-    SLACK_BOT_TOKEN: xoxb-214407968934-8110370703840-PVbwKXDu36PNnCGijkR9z3PE
 phases:
   install:
     runtime-versions:
@@ -17,6 +16,14 @@ phases:
     commands:
       - |
         #!/bin/bash
+        echo "Retrieving SLACK_BOT_TOKEN from AWS Secrets Manager..."
+        SLACK_BOT_TOKEN=$(aws secretsmanager get-secret-value --secret-id "arn:aws:secretsmanager:ca-central-1:417873687559:secret:SlackBotToken-rY8Mqn" --output text --query SecretString)
+
+        if [ -z "$SLACK_BOT_TOKEN" ]; then
+          echo "Error: Failed to retrieve SLACK_BOT_TOKEN from Secrets Manager."
+          exit 1
+        fi
+        
         echo "Reading test exit code..."
         
         if [ ! -f test_exit_code.txt ]; then
